services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psd00
      POSTGRES_DB: booksdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - postgres
    ports:
      - "3001:3000"

volumes:
  postgres_data: